# BE CAREFUL - Dont fuck around with this file
# DONT TOUCH THESE 3 LINES !!!
baseurl = "/"
languageCode = "en-us"
languageLang = "en"
MetaDataFormat = "toml"
#
enableRobotsTXT = true
enableGitInfo = false
# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
#canonifyurls = true
#uglyurls = true
summaryLength = 110
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# Multilangues setup
DefaultContentLanguage = "en"
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  posts = "/:year/:month/:title/"

###
#
# Website main infos
#
###
title = "Bulgo"
subtitle = "bulma css"
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud."
author = " "


[Params]
# logo = "img/logo.svg"
title = "Bulgo"
subtitle = "Bulma css & hugo"

metadescription = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud."
# Bulgo customized elements
navbar_color = "white"
navbar_left_stripe = "roy"

page_color = ""
page_left_stripe = ""
page_background_image = ""

footer_color = "white"
footer_left_stripe = "roy"



copyright_note_fr = "Tous droits réservés."
copyright_note_en = "All rights reserved."

company_name= "Studio60"
company_phone = "+41 123 456 78"
company_mail = "loremipsum@mail.com"

 facebook = "https://facebook.com/"
 twitter = "https://twitter.com/"
 instagram = "https://instagram.com/"
 youtube = "https://youtube.com/"
 linkedin = "https://linkedin.com/"
 reddit = "https://reddit.com/"
