baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Bulgo"
subtitle = "Bulma css & hugo"
# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[permalinks]
  posts = "/:year/:month/:title/"

[Params]
 logo = "img/bulgo-logotype.svg"

# Bulgo customized elements
navbar_color = " "
navbar_left_stripe = " "
page_color = ""
page_left_stripe = ""
page_background_image = ""

footer_color = ""
footer_left_stripe = ""

copyright_note_en = "All rights reserved."

company_name= "Studio60"
company_description= "Your web agency based in Lausanne [ch]. We design and develop things for the web."
company_phone =  "+41 (0)79 927 54 63"
company_logo = "img/studio60-logotype.svg"
github = "https://github.com/theStudio60"

[Params.navbar]
menuLabel = "MENU"
menuLinkUrl_01 = "/"
menuLinkName_01 = "home"
menuLinkIcon_01 = ""

menuLinkUrl_02 = ""
menuLinkName_02 = "about"
menuLinkIcon_02 = ""

menuLinkUrl_03 = ""
menuLinkName_03 = "Offers"
menuLinkIcon_03 = ""

menuLinkUrl_04 = ""
menuLinkName_04 = "contact"
menuLinkIcon_04 = ""

menuLinkUrl_05 = "https://github.com/theStudio60/bulgo"
menuLinkName_05 = ""
menuLinkIcon_05 = "github"


[Params.homepage_01]
title = "Bulgo"
subtitle = "A Bulma css theme written for hugo ssg"
paragraph = "This hugo theme was designed and developed by "

paragraph_linkUrl = "https://studio60.ch"
paragraph_linkName = "@Studio60"

backgroundImageSrc = "images/vinyl_playing_bw.jpg"

linkUrl_01 = "https://STUDIO60.ch"
linkIcon_01 = "arrow-right"
linkName_01 = "Contact Us !"

linkUrl_02 = "https://github.com/theStudio60/bulgo"
linkIcon_02 = "github"
linkName_02 = "See this project on github"

[Params.homepage_02]
topMiniTitle = "another static website made with hugo"
title = "Hello world 🙂"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
paragraph = "This section has a white background and a colored stripe on the left."
imageSrc = "images/k7.png"
imageAlt = "Bulgo tape"

linkUrl_01 = ""
linkIcon_01 = "list"
linkName_01 = "this is a link"



[Params.homepage_03_01]
topMiniTitle = "this is a yellow section"
title = "this is how a yellow section looks like"
subtitle = "we use arial black on all headings"
paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  "

imageSrc = "images/bg-img-home-yellow.png"
imageAlt = "Vinyls and tapes yellow"

linkUrl_01 = ""
linkIcon_01 = " "
linkName_01 = " "

[Params.homepage_03_02]
topMiniTitle = "this is an orange section 🍊"
title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "
subtitle = " "
paragraph = ""

imageSrc = "images/rca-orange.jpg"
imageAlt = "orange vinyl label"

linkUrl_01 = ""
linkIcon_01 = " "
linkName_01 = "Links are Orange on white containers"

[Params.homepage_03_03]
topMiniTitle = "lifestyle & stuff"
title = "Using a good earphones set is important"
subtitle = " "
paragraph = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. "

imageSrc = "images/red-earphone_music_lifestyle.jpg"
imageAlt = "earphones"

linkUrl_01 = ""
linkIcon_01 = " "
linkName_01 = "Links are Orange on white containers"
 
[Params.homepage_04]
topMiniTitle = "this is a yellow section"
title = "section body yellow"
subtitle = "arial black on all headings"
paragraph = "Homepage 03.03 Paragraph : Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

imageSrc = "images/red-earphone_music_lifestyle.jpg"
imageAlt = "earphones"

linkUrl_01 = ""
linkIcon_01 = " "
linkName_01 = "Links are Orange on white containers"
 
