baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Title"
subtitle = "bulgo hugo theme"
# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[permalinks]
  posts = "/:year/:month/:title/"

[Params]
 logo = "img/bulgo-logotype.svg"

# Bulgo customized elements
navbar_color = " "
navbar_left_stripe = " "
page_color = ""
page_left_stripe = ""
page_background_image = ""

footer_color = ""
footer_left_stripe = ""

copyright_note_en = "All rights reserved."

company_name= "Studio60"
company_website= "https://studio60.ch"
company_description= ""
company_phone =  "+41 (0)12 345 67 89"
company_logo = "img/studio60-logotype.svg"
github = "https://github.com/theStudio60"

[Params.navbar]
menuLabel = "MENU"
menuLinkUrl_01 = "/"
menuLinkName_01 = "home"
menuLinkIcon_01 = ""

menuLinkUrl_02 = ""
menuLinkName_02 = "about"
menuLinkIcon_02 = ""

menuLinkUrl_03 = ""
menuLinkName_03 = "Offers"
menuLinkIcon_03 = ""

menuLinkUrl_04 = ""
menuLinkName_04 = "contact"
menuLinkIcon_04 = ""

menuLinkUrl_05 = "https://github.com/theStudio60/bulgo"
menuLinkName_05 = ""
menuLinkIcon_05 = "github"


[Params.homepage_01]
title = "Hello world"
subtitle = "lorem ipsum"
paragraph = "bulgo : hugo ssg theme"

paragraph_linkUrl = "https://studio60.ch"
paragraph_linkName = "@Studio60"

backgroundImageSrc = "images/vinyl_playing_bw.jpg"

linkUrl_01 = "https://STUDIO60.ch/contact"
linkIcon_01 = "arrow-right"
linkName_01 = "Contact Us !"

linkUrl_02 = "https://github.com/theStudio60/bulgo"
linkIcon_02 = "github"
linkName_02 = "See this project on github"

[Params.homepage_02]
topMiniTitle = "another static website made with hugo"
title = "Hello world 🙂"
subtitle = "lorem"
paragraph = "This section has a white background and a colored stripe on the left."
imageSrc = "images/k7.png"
imageAlt = "Bulgo tape"

linkUrl_01 = ""
linkIcon_01 = "list"
linkName_01 = "this is a    link"



[Params.homepage_03_01]
topMiniTitle = "this is a yellow section"
title = ""
subtitle = "we use arial black on all headings"
paragraph = ""

imageSrc = "images/bg-img-home-yellow.png"
imageAlt = "Vinyls and tapes yellow"

linkUrl_01 = ""
linkIcon_01 = " "
linkName_01 = " "

[Params.homepage_03_02]
topMiniTitle = "orange section"
title = "title"
subtitle = "subtitle"
paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

imageSrc = "images/rca-orange.jpg"
imageAlt = "orange vinyl label"

linkUrl_01 = ""
linkIcon_01 = "facebook"
linkName_01 = "link"

[Params.homepage_03_03]
topMiniTitle = "lifestyle & stuff"
title = "lorem ipsum"
subtitle = " "
paragraph = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

imageSrc = "images/red-earphone_music_lifestyle.jpg"
imageAlt = "earphones"

linkUrl_01 = ""
linkIcon_01 = " "
linkName_01 = "Links are Orange on white containers"
 
[Params.homepage_04]
topMiniTitle = "this is a yellow section"
title = "section body yellow"
subtitle = "arial black on all headings"
paragraph = "Homepage 03.03 Paragraph : Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat."

imageSrc = "images/red-earphone_music_lifestyle.jpg"
imageAlt = "earphones"

linkUrl_01 = ""
linkIcon_01 = " "
linkName_01 = "Links are Orange on white containers"
 